services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seedwork-devcontainer
    volumes:
      - ..:/workspaces/drifterapps-seed-work:cached
      - ${USER_PROFILE}/.ssh:/home/vscode/.ssh:ro
      - ${USER_PROFILE}/.gitconfig:/home/vscode/.gitconfig:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - '2224:22'
