name: Linter

on:
  push:
    branches: [main]
    paths-ignore:
      [
        "docs/**",
        ".vscode/**",
        "**/*.md",
        "**/ci-cd.yml",
        "**/codeql-analysis.yml",
        "**/mutation-tests.yml",
        "**/test-results.yml",
      ]

  pull_request:
    paths-ignore:
      [
        "docs/**",
        ".vscode/**",
        "**/*.md",
        "**/ci-cd.yml",
        "**/codeql-analysis.yml",
        "**/mutation-tests.yml",
        "**/test-results.yml",
      ]

  workflow_dispatch:

jobs:
  csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json

      - name: Lint C# files with dotnet format
        id: lint
        run: dotnet format --severity error --verbosity diagnostic --report ./linter-report || true

      - name: Save report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-format-report
          path: ./linter-report/*

      - name: Check for errors
        if: ${{ steps.lint.outcome != 'success' }}
        run: echo "::error::dotnet format found issues in the code. Please fix them."
