name: linter

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: linter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Lint C# files with dotnet format
        id: lint
        run: dotnet format --severity error --verbosity diagnostic --report ./linter-report || true

      - name: Save report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-format-report
          path: ./linter-report/*

      - name: Check for errors
        if: ${{ steps.lint.outcome != 'success' }}
        run: echo "::error::dotnet format found issues in the code. Please fix them."
