name: linter

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: linter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_changes:
    uses: patmoreau/renovate-config/.github/workflows/check-changes-action.yml@main
    with:
      base_ref: ${{ github.base_ref }}
      file_patterns: ${{ vars.CODE_FILE_PATTERNS }}

  csharp:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.code_was_changed == true }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Lint C# files with dotnet format
        id: lint
        run: dotnet format --severity error --verbosity diagnostic --report ./linter-report || true

      - name: Save report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-format-report
          path: ./linter-report/*

      - name: Check for errors
        if: ${{ steps.lint.outcome != 'success' }}
        run: echo "::error::dotnet format found issues in the code. Please fix them."

  required_check:
    needs: [check_changes, csharp]
    runs-on: ubuntu-latest
    if: (needs.check_changes.outputs.code_was_changed == 'false') || (needs.csharp.result == 'success')
    steps:
      - name: Linter completed
        run: |
          echo "::set-output name=Linter completed::success"
