name: renovate

on:
  schedule:
    - cron: '0 3 * * *' # Run daily at 3 AM

  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        run: renovate
